[package]
name = "rustspyder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
assert_cmd = { version = "2.1.2" }
predicates = { version = "3.1.3" }
proc-macro2 = { version = "1.0.105" }
